language: objective-c

before_install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/travis-testtap
  - brew tap --repair
  - brew update

env:
  - PACKAGE=git-init-gforge

script:
  - brew audit $PACKAGE
  - brew install -v $PACKAGE

notifications:
  email:
    on_success: never
    on_failure: always
